version: 2
jobs:

  checkout:
    docker: &docker
      - image: circleci/node:8
    working_directory: &working_directory ~/hash-code-2018-training
    steps:
      - checkout
      - save_cache:
          key: &checkout_cache_key checkout-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - *working_directory

  install-dependencies:
    docker: *docker
    working_directory: *working_directory
    steps:
      - restore_cache: &restore_checkout_cache
          keys:
            - *checkout_cache_key
      - restore_cache: &restore_dependency_cache
          keys: 
            - &dependency_cache_key dependency-cache-{{ checksum "package.json" }}
      - run:
          command: npm install
      - save_cache:
          key: *dependency_cache_key
          paths:
            - ./node_modules

  test:
    docker: *docker
    working_directory: *working_directory
    steps:
      - restore_cache: *restore_checkout_cache
      - restore_cache: *restore_dependency_cache
      - run:
          command: npm test

  data-set-1:
    docker: *docker
    working_directory: *working_directory
    steps:
      - restore_cache: *restore_checkout_cache
      - restore_cache: *restore_dependency_cache
      - run:
          command: npm run input1

  data-set-2:
    docker: *docker
    working_directory: *working_directory
    steps:
      - restore_cache: *restore_checkout_cache
      - restore_cache: *restore_dependency_cache
      - run:
          command: npm run input2

  data-set-3:
    docker: *docker
    working_directory: *working_directory
    steps:
      - restore_cache: *restore_checkout_cache
      - restore_cache: *restore_dependency_cache
      - run:
          command: npm run input3

  data-set-4:
    docker: *docker
    working_directory: *working_directory
    steps:
      - restore_cache: *restore_checkout_cache
      - restore_cache: *restore_dependency_cache
      - run:
          command: npm run input4

workflows:
  version: 2
  try-everything:
    jobs:
      - checkout
      - install-dependencies:
          requires:
            - checkout
      - test:
          requires:
            - install-dependencies
      - data-set-1: &data_set_requires
          requires:
            - install-dependencies
      - data-set-2: *data_set_requires
      - data-set-3: *data_set_requires
      - data-set-4: *data_set_requires
